services:
  status-light:
    container_name: status-light
    image: status-light
    build: .
    environment:
      - NODE_ENV=production
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped