version: '3.8'
services:
  status-light:
    build: .
    environment:
      - NODE_ENV=production
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped